### ISSUE TITLE
Using PathValue

### ISSUE THREAD

**Issue by carlmjohnson** [jba/muxpatterns#2]
I'm trying to use muxpatterns in my app to test whether it would work as a replacement for Chi, and I ran into a roadblock. In my current handlers, I have code like

```go
param := chi.URLParam(r, "name")
```

To make this work with muxpatterns, I would need to pass the mux to the handlers, which greatly complicates the code.

```go
param := app.mux.PathValue(r, "name")
```

This won't be a problem in the final stdlib code, where I could just do `r.PathValue("name")`, so I would rather not have to replumb my app just for this experiment.

What if you smuggle the PathValues through r.Context() for now? You could then retrieve them with `param := muxpatterns.PathValue(r, "name")`. It would make using the experiment easier, as well as switching to the std lib when the experiment is over.

**Comment by carlmjohnson** [comment]
Another problem is that the lookup of PathValue doesn't work if r has been replaced by middleware. Using a context would solve this.

**Comment by jba** [comment]
Good idea. I should have done that from the beginning.
